### PR TITLE
Update index.vue

### PR DESCRIPTION
**Pull request by bhavana-netlify**

### CODE REVIEW

**Comment by bhavana-netlify** [comment]
Leave comments from the demo
<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 94.0.4606.61 on Mac OS 10.15.7
Viewport:  1792 x 1009 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=94.0&resolution=1792x1009&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=61a79c161888f13b594b9ccb&resolution=resolved)

**Comment by bhavana-netlify** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 94.0.4606.61 on Mac OS 10.15.7
Viewport:  1792 x 1009 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=94.0&resolution=1792x1009&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=61a79c68fd023a3a50462038&resolution=resolved)

**Comment by chrishannaby** [comment]
screenshot


<details><summary>Browser metadata</summary>





```
Path:      /cart/
Browser:   Chrome 96.0.4664.55 on Mac OS 10.15.7
Viewport:  1792 x 901 @2x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2Fcart%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=96.0&resolution=1792x901&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/cart/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=61a7ef44f10ac5b464ef1061&resolution=resolved)

**Comment by rsedighi** [comment]
The font is off, and word is misspelled @rsedighi 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /cart/
Browser:   Chrome 96.0.4664.45 on Mac OS 10.15.7
Viewport:  1356 x 700 @1.399999976158142x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2Fcart%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=96.0&resolution=1356x700&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/cart/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=6202b95adbcc4f482b4d3aeb&resolution=resolved)

**Comment by rsedighi** [comment]
Some white text, and typo with font... @rsedighi 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /product/thorium-ar-hoody-dracaena/
Browser:   Chrome 96.0.4664.45 on Mac OS 10.15.7
Viewport:  1327 x 700 @1.399999976158142x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2Fproduct%2Fthorium-ar-hoody-dracaena%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=96.0&resolution=1327x700&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/product/thorium-ar-hoody-dracaena/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=623b347ee2ca5d09d27c32c5&resolution=resolved)

**Comment by rsedighi** [comment]
Testing this deploy preview!

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /product/thorium-ar-hoody-dracaena/
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1374 x 786 @2.200000047683716x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2Fproduct%2Fthorium-ar-hoody-dracaena%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1374x786&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/product/thorium-ar-hoody-dracaena/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=63a5005f35a1fb01ab9f7fe6&resolution=resolved)

**Comment by rsedighi** [comment]
@rsedighi the page is not responsive, please look into this!

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /
Browser:   Chrome 108.0.0.0 on Mac OS 10.15.7
Viewport:  1645 x 891 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2F&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=108.0&resolution=1645x891&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=63b728d2947e7e0a623bfe26&resolution=resolved)

**Comment by rsedighi** [comment]
@rsedighi 

screenshot


<details><summary>Browser metadata</summary>





```
Path:      /product/Cerium-LT-Hoody-Galactica
Browser:   Chrome 109.0.0.0 on Mac OS 10.15.7
Viewport:  1651 x 880 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-30--ecommerce-vue.netlify.app%2Fproduct%2FCerium-LT-Hoody-Galactica&os=OS%20X&os_version=Catalina&browser=Chrome&browser_version=109.0&resolution=1651x880&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-30--ecommerce-vue.netlify.app/product/Cerium-LT-Hoody-Galactica) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a79a09a6d08c0007c73fad&commentID=63eaa1b4e3578f32024025b1&resolution=resolved)

**Pull request merged**
